version: "3.9"

services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "ecothon2024"
      POSTGRES_USER: "ecothon2024"
      POSTGRES_DB: "ecothon2024"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ecothon2024 -U ecothon2024" ]
      interval: 5s
      timeout: 60s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_CONN=postgresql://ecothon2024:ecothon2024@db:5432/ecothon2024
  nginx:
    build:
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  db_data:
